const theme = {
  color: {
    light: '#ffffff',
    dark: '#292a31',
    positive: '#069697',
    positiveLightXX: '#e8f5f5',
    positiveLightX: '#bbe2e2',
    positiveLight: '#33a9a9',
    positiveDark: '#057b7c',
    border: '#d2d2d6',
    borderLight: '#e1e1e3',
    borderDark: '#b4b4bb',
    danger: '#f44336',
    dangerLightX: '#fccbcb',
    dangerLight: '#f6655a',
    dangerDark: '#c8372d',
    pannelLight: '#f0f1f9',
    text: '#5a5b6a',
    textLight: '#787885',
    textDark: '#4a4b57',
  },
  height: {
    row: '3rem',
    elementSmall: '2.25rem',
    elementContainer: '5rem',
    header:'4rem',
    iconSmall:'1.75rem',
    iconMedium:'2.5rem',
    options:'2.25rem',
  },
  width:{
    dropMenuMedium:'12rem',
  },
  padding: {
    elementSmall: '1rem',
    elementMedium: '2rem',
    container:'2rem',
    dropMenu:'0.75rem',
    labelSmall:'0.25rem',
  },
  margin: {
    elementSmall: '0.5rem',
    elementMedium: '2rem',
    small: '1rem',
    medium: '2rem',
    container:'2rem',
    labelSmall:'0.25rem',
  },
  radius: {
    small: '0.2rem',
    medium: '0.3rem',
  },
  fontSize: {
    elementSmall: '1rem',
    elementLabel: '1rem',
    message: '0.75rem',
    label:'1rem',
  },
  fontFamily: {
    thin: 'lato-thin',
    light: 'lato-light',
    regular: 'lato-regular',
    bold: 'lato-bold',
    hard: 'lato-black',
  },
};

export default theme;
